// Single source of truth for all tools metadata
// The dashboard, search, sitemap, and extension all read from this file.

export type ToolCategory =
  | "image"
  | "document"
  | "audio-video"
  | "text-code"
  | "productivity"
  | "privacy-security"
  | "design"
  | "data"
  | "web-seo"
  | "writing";

export interface Tool {
  id: string;
  name: string;
  description: string;
  category: ToolCategory;
  icon: string;
  tags: string[];
  isNew?: boolean;
  isImplemented?: boolean;
  /** Workflow Builder config — Rule 55: add now, fill in as workflow feature is built */
  workflowConfig?: {
    acceptsInput: string[];
    producesOutput: string[];
    requiredConfig: string[];
  };
}

export const categoryMeta: Record<
  ToolCategory,
  { label: string; icon: string }
> = {
  image: { label: "Image", icon: "Image" },
  document: { label: "Document", icon: "FileText" },
  "audio-video": { label: "Audio & Video", icon: "Play" },
  "text-code": { label: "Text & Code", icon: "Code2" },
  productivity: { label: "Productivity", icon: "Zap" },
  "privacy-security": { label: "Privacy & Security", icon: "ShieldCheck" },
  design: { label: "Design", icon: "Palette" },
  data: { label: "Data", icon: "Database" },
  "web-seo": { label: "Web & SEO", icon: "Globe" },
  writing: { label: "Writing", icon: "PenLine" },
};

export const tools: Tool[] = [
  // ── BATCH 1: Text & Code (no heavy deps) ──────────────────────────────────
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and minify JSON with syntax highlighting.",
    category: "text-code",
    icon: "Braces",
    tags: ["json", "format", "validate", "minify", "pretty", "code"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "text-case",
    name: "Text Case Converter",
    description:
      "Convert between camelCase, snake_case, UPPER, Title, kebab-case and more.",
    category: "text-code",
    icon: "CaseSensitive",
    tags: ["case", "text", "camel", "snake", "pascal", "kebab", "upper", "lower"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "word-count",
    name: "Word Count",
    description:
      "Words, characters, sentences, reading time, and Flesch readability score.",
    category: "writing",
    icon: "AlignLeft",
    tags: ["word", "count", "characters", "reading", "flesch", "readability"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description:
      "Cryptographically secure passwords and passphrases with strength meter.",
    category: "privacy-security",
    icon: "KeyRound",
    tags: ["password", "generate", "secure", "crypto", "passphrase", "random"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "base64",
    name: "Base64 Encoder / Decoder",
    description: "Encode and decode Base64 for text and files.",
    category: "text-code",
    icon: "Binary",
    tags: ["base64", "encode", "decode", "text", "file", "data url"],
    isNew: true,
    isImplemented: true,
  },

  // ── Coming soon ───────────────────────────────────────────────────────────
  {
    id: "background-remover",
    name: "Background Remover",
    description: "Remove image backgrounds with AI running in your browser. Download as transparent PNG.",
    category: "image",
    icon: "Scissors",
    tags: ["background", "remove", "transparent", "png", "photo", "cutout", "ai"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "image-compressor",
    name: "Image Compressor",
    description: "Compress JPG, PNG, and WebP images without visible quality loss.",
    category: "image",
    icon: "PackageMinus",
    tags: ["compress", "image", "jpg", "png", "webp", "size", "optimize"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "pdf-merger",
    name: "PDF Merger & Splitter",
    description: "Merge multiple PDFs or extract page ranges. Reorder files before merging.",
    category: "document",
    icon: "FilePlus",
    tags: ["pdf", "merge", "split", "combine", "extract", "pages"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "image-converter",
    name: "Image Format Converter",
    description: "Convert between JPG, PNG, WebP, AVIF, GIF, and more.",
    category: "image",
    icon: "RefreshCw",
    tags: ["convert", "image", "jpg", "png", "webp", "avif", "format"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "image-resizer",
    name: "Image Resizer",
    description: "Resize by pixels or percentage, with social media presets and aspect ratio lock.",
    category: "image",
    icon: "Crop",
    tags: ["resize", "crop", "image", "dimensions", "aspect ratio", "social"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "pdf-to-image",
    name: "PDF to Image",
    description: "Export PDF pages as PNG or JPG at 72–300 DPI. Thumbnail grid with per-page download.",
    category: "document",
    icon: "FileImage",
    tags: ["pdf", "image", "png", "jpg", "convert", "export", "dpi"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, SHA-384, SHA-512 hashes for text and files.",
    category: "privacy-security",
    icon: "Hash",
    tags: ["hash", "md5", "sha256", "sha512", "checksum", "crypto", "file integrity"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions with real-time match highlighting and group extraction.",
    category: "text-code",
    icon: "Search",
    tags: ["regex", "regular expression", "test", "match", "pattern", "flags"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "qr-code",
    name: "QR Code Generator",
    description: "Generate styled QR codes for URLs, WiFi, vCard, email, SMS & more — with logos, gradients, dot styles, and PNG/SVG export.",
    category: "productivity",
    icon: "QrCode",
    tags: ["qr", "qrcode", "generate", "url", "text", "wifi", "vcard", "email", "logo", "svg", "gradient"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    description: "Convert length, weight, temperature, area, volume, speed, data, and time.",
    category: "productivity",
    icon: "ArrowLeftRight",
    tags: ["unit", "convert", "length", "weight", "temperature", "area", "speed", "data"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "color-converter",
    name: "Color Picker & Converter",
    description: "Convert between HEX, RGB, HSL, HSV, CMYK. WCAG contrast ratios and color history.",
    category: "design",
    icon: "Pipette",
    tags: ["color", "hex", "rgb", "hsl", "picker", "convert", "wcag", "contrast"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "markdown-to-html",
    name: "Markdown → HTML",
    description: "Convert Markdown to HTML with live split-pane preview and formatting toolbar.",
    category: "text-code",
    icon: "FileCode",
    tags: ["markdown", "html", "convert", "preview", "md", "editor"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "csv-json",
    name: "CSV ↔ JSON",
    description: "Convert between CSV and JSON. Custom delimiters, preview table, file upload.",
    category: "data",
    icon: "Table",
    tags: ["csv", "json", "convert", "data", "spreadsheet", "delimiter"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "color-palette",
    name: "Color Palette Extractor",
    description: "Extract dominant colors from any image with HEX, RGB, and HSL values.",
    category: "design",
    icon: "Palette",
    tags: ["color", "palette", "extract", "image", "swatch", "dominant"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "diff-checker",
    name: "Diff Checker",
    description: "Compare two texts with line, word, or character diffs. Split and unified views.",
    category: "text-code",
    icon: "GitCompare",
    tags: ["diff", "compare", "text", "difference", "changes", "patch"],
    isNew: true,
    isImplemented: true,
  },

  // ── BATCH 5: Part 2 tools ──────────────────────────────────────────────────
  {
    id: "url-encoder",
    name: "URL Encoder / Decoder",
    description: "Encode or decode URLs in 4 modes: URI Component, Full URI, Base64, Form. Parses query params.",
    category: "web-seo",
    icon: "Globe",
    tags: ["url", "encode", "decode", "uri", "base64", "query", "params", "percent"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "base-converter",
    name: "Number Base Converter",
    description: "Convert numbers between Binary, Octal, Decimal, Hex, Base32, Base36. BigInt precision.",
    category: "text-code",
    icon: "Binary",
    tags: ["binary", "hex", "octal", "decimal", "base", "convert", "number", "bigint"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "char-counter",
    name: "Character & Byte Counter",
    description: "Count chars, words, bytes (UTF-8/16), reading time. Word frequency, platform limits.",
    category: "writing",
    icon: "AlignLeft",
    tags: ["character", "byte", "counter", "utf8", "utf16", "word", "frequency", "reading"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text by paragraphs, sentences, or words. Plain, HTML, or Markdown output.",
    category: "writing",
    icon: "PenLine",
    tags: ["lorem", "ipsum", "placeholder", "text", "generator", "paragraph", "dummy"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode JSON Web Tokens client-side. View header, payload, expiry, and standard claims.",
    category: "privacy-security",
    icon: "ShieldCheck",
    tags: ["jwt", "json", "token", "decode", "auth", "bearer", "claims", "expiry"],
    isNew: true,
    isImplemented: true,
  },

  // ── BATCH 6: Part 2 remaining 15 tools ────────────────────────────────────
  {
    id: "gradient-generator",
    name: "CSS Gradient Generator",
    description: "Create linear, radial, and conic CSS gradients visually. Copy CSS or download as PNG.",
    category: "design",
    icon: "Palette",
    tags: ["css", "gradient", "linear", "radial", "conic", "color", "background"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "color-contrast",
    name: "Color Contrast Checker",
    description: "WCAG 2.1 AA/AAA compliance checker. Live preview with hex color pickers.",
    category: "design",
    icon: "Pipette",
    tags: ["color", "contrast", "wcag", "accessibility", "a11y", "aa", "aaa"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "json-excel",
    name: "JSON ↔ Excel",
    description: "Convert JSON to Excel (.xlsx/CSV) or Excel to JSON. Live table preview, nested flattening.",
    category: "data",
    icon: "Table",
    tags: ["json", "excel", "xlsx", "csv", "convert", "spreadsheet", "data"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "image-watermark",
    name: "Image Watermark",
    description: "Add text or logo watermarks to images. Position, opacity, angle, tiled mode. 100% client-side.",
    category: "image",
    icon: "FileImage",
    tags: ["watermark", "image", "text", "logo", "canvas", "brand"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "pdf-compressor",
    name: "PDF Compressor",
    description: "Compress PDF files by rasterising pages. Configurable quality and DPI. No upload required.",
    category: "document",
    icon: "PackageMinus",
    tags: ["pdf", "compress", "reduce", "size", "optimize"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "text-to-speech",
    name: "Text to Speech",
    description: "Convert text to speech in-browser. Choose voice, rate, pitch, volume. Works offline.",
    category: "productivity",
    icon: "Play",
    tags: ["text", "speech", "tts", "voice", "read", "audio"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "speech-to-text",
    name: "Speech to Text",
    description: "Real-time speech transcription via microphone. 20+ languages. Chrome/Edge only.",
    category: "productivity",
    icon: "AlignLeft",
    tags: ["speech", "transcribe", "microphone", "stt", "voice", "recognition"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "pomodoro",
    name: "Pomodoro Timer",
    description: "Drift-free focus timer with auto-start, desktop notifications, daily stats, and persistent streaks. Background-safe and configurable.",
    category: "productivity",
    icon: "Zap",
    tags: ["pomodoro", "timer", "focus", "productivity", "work", "break", "notifications", "stats"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "aspect-ratio",
    name: "Aspect Ratio Calculator",
    description: "Calculate and simplify aspect ratios. Equivalent resolutions, named ratio detection.",
    category: "design",
    icon: "Crop",
    tags: ["aspect", "ratio", "16:9", "4:3", "resolution", "dimensions", "responsive"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "html-entities",
    name: "HTML Entity Encoder",
    description: "Encode/decode HTML entities in Basic, Named, or Numeric modes. Entity reference table.",
    category: "text-code",
    icon: "Code2",
    tags: ["html", "entity", "encode", "decode", "amp", "lt", "gt", "special chars"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "timezone-converter",
    name: "Timezone Converter",
    description: "Convert date/time across any IANA timezone. Native Intl API, always DST-accurate.",
    category: "productivity",
    icon: "Globe",
    tags: ["timezone", "convert", "time", "utc", "dst", "iana", "world clock"],
    isNew: true,
    isImplemented: true,
  },

  // ── BATCH 7: The 4 missing tools (21-24) ──────────────────────────────────
  {
    id: "image-to-text",
    name: "Image to Text (OCR)",
    description: "Extract text from images using Tesseract.js. 10 languages, confidence scores. 100% in-browser.",
    category: "image",
    icon: "FileText",
    tags: ["ocr", "image", "text", "tesseract", "extract", "scan", "handwriting"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "exif-viewer",
    name: "EXIF Viewer & Remover",
    description: "View and remove EXIF, GPS, IPTC metadata from images. GPS privacy warning with map link.",
    category: "privacy-security",
    icon: "ShieldCheck",
    tags: ["exif", "metadata", "gps", "privacy", "location", "iptc", "xmp", "remove"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "svg-optimizer",
    name: "SVG Optimizer",
    description: "Optimise SVG files with SVGO in-browser. 14 options, side-by-side preview, up to 80% reduction.",
    category: "design",
    icon: "Crop",
    tags: ["svg", "optimize", "minify", "svgo", "vector", "compress", "clean"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "favicon-generator",
    name: "Favicon Generator",
    description: "Generate all favicon sizes from one image. 7 PNGs, .ico, PWA manifest, HTML snippet in a ZIP.",
    category: "web-seo",
    icon: "Image",
    tags: ["favicon", "icon", "png", "ico", "pwa", "manifest", "generator"],
    isNew: true,
    isImplemented: true,
  },

  // ── PART 3: Tools 41–50 ───────────────────────────────────────────────────
  {
    id: "audio-converter",
    name: "Audio Format Converter",
    description: "Convert audio between MP3, WAV, FLAC, OGG, AAC and more. FFmpeg WASM, no upload.",
    category: "audio-video",
    icon: "Music",
    tags: ["audio", "convert", "mp3", "wav", "flac", "ogg", "aac", "ffmpeg"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "video-to-gif",
    name: "Video to GIF Converter",
    description: "Convert video clips to animated GIF or WebP. Two-pass palette, no upload.",
    category: "audio-video",
    icon: "Video",
    tags: ["video", "gif", "webp", "animate", "convert", "ffmpeg", "clip"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "audio-trimmer",
    name: "Audio Trimmer",
    description: "Trim audio with waveform editor. Lossless, instant, no re-encoding.",
    category: "audio-video",
    icon: "Scissors",
    tags: ["audio", "trim", "cut", "waveform", "mp3", "wav", "ffmpeg"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "image-to-pdf",
    name: "Image to PDF",
    description: "Combine multiple images into a PDF. A4, Letter, Fit-to-image, margin control.",
    category: "document",
    icon: "FileOutput",
    tags: ["image", "pdf", "convert", "merge", "jpg", "png", "a4"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "barcode-generator",
    name: "Barcode Generator",
    description: "Generate CODE128, EAN-13, UPC, ITF-14 barcodes. SVG and PNG download.",
    category: "design",
    icon: "ScanBarcode",
    tags: ["barcode", "qr", "ean13", "code128", "upc", "svg", "png", "retail"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "fake-data-generator",
    name: "Fake Data Generator",
    description: "Generate test data: names, emails, UUIDs. JSON, CSV, SQL, TypeScript output.",
    category: "data",
    icon: "Database",
    tags: ["fake", "data", "test", "mock", "json", "csv", "sql", "seed"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "jwt-generator",
    name: "JWT Generator & Verifier",
    description: "Sign and verify JWTs with HS256/RS256. Colour-coded token, verify tab.",
    category: "privacy-security",
    icon: "KeyRound",
    tags: ["jwt", "token", "sign", "verify", "hs256", "rs256", "auth"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "cron-builder",
    name: "Cron Expression Builder",
    description: "Build cron schedules visually. Human-readable description, next 5 runs.",
    category: "productivity",
    icon: "Clock",
    tags: ["cron", "schedule", "expression", "unix", "timer", "recurring"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "box-shadow",
    name: "CSS Box Shadow Generator",
    description: "Design multi-layer box shadows. Live preview, presets, CSS and Tailwind output.",
    category: "design",
    icon: "Layers",
    tags: ["css", "box-shadow", "shadow", "design", "tailwind", "generator"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "border-radius",
    name: "CSS Border Radius Visualiser",
    description: "Visualise border-radius per corner. Linked/independent, px and % units.",
    category: "design",
    icon: "Wand2",
    tags: ["css", "border-radius", "corners", "shape", "design", "rounded"],
    isNew: true,
    isImplemented: true,
  },
  // ── Tools 51–60 ─────────────────────────────────────────────
  {
    id: "meta-tag-generator",
    name: "Meta Tag Generator",
    description: "Generate SEO meta tags with live social preview.",
    category: "web-seo",
    icon: "Globe",
    tags: ["seo", "meta", "open-graph", "twitter", "html", "canonical"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "og-preview",
    name: "Open Graph Preview",
    description: "Preview how any URL looks when shared on social media.",
    category: "web-seo",
    icon: "Share2",
    tags: ["open-graph", "og", "twitter", "facebook", "social", "preview", "meta"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "sitemap-generator",
    name: "Sitemap XML Generator",
    description: "Build sitemap.xml from URL list with priority and changefreq.",
    category: "web-seo",
    icon: "FileCode",
    tags: ["sitemap", "xml", "web-seo", "urls", "crawl"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "robots-txt",
    name: "robots.txt Generator",
    description: "Generate robots.txt with bot rules, presets, and validation.",
    category: "web-seo",
    icon: "ShieldCheck",
    tags: ["robots", "web-seo", "crawl", "bot", "googlebot", "disallow"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "gps-map",
    name: "Image GPS Map (EXIF)",
    description: "View photo location on map. Extracts GPS EXIF metadata.",
    category: "image",
    icon: "MapPin",
    tags: ["gps", "exif", "map", "location", "photo", "latitude", "metadata"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "markdown-table",
    name: "Markdown Table Generator",
    description: "Create Markdown tables in a visual grid. CSV import, HTML export.",
    category: "text-code",
    icon: "Table",
    tags: ["markdown", "table", "csv", "html", "grid", "documentation"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "unix-timestamp",
    name: "Unix Timestamp Converter",
    description: "Convert timestamps to dates and back. Live mode, 6 timezones.",
    category: "productivity",
    icon: "Clock",
    tags: ["unix", "timestamp", "date", "time", "epoch", "timezone", "iso"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "ip-lookup",
    name: "IP Address Lookup",
    description: "Look up geolocation, ISP, ASN, timezone & more for any IP with provider fallback, distance-from-you, map, and copy-as-JSON. Auto-detects yours.",
    category: "productivity",
    icon: "Wifi",
    tags: ["ip", "geolocation", "isp", "asn", "network", "lookup", "ipv6", "timezone"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "random-color",
    name: "Random Colour Generator",
    description: "Generate harmonious palettes: analogous, triadic, neon and more.",
    category: "design",
    icon: "Palette",
    tags: ["color", "colour", "palette", "generator", "css", "design", "harmony"],
    isNew: true,
    isImplemented: true,
  },
  {
    id: "code-formatter",
    name: "Code Formatter / Beautifier",
    description: "Format JS, TS, JSON, CSS, HTML via Prettier. Lazy CDN load.",
    category: "text-code",
    icon: "Code2",
    tags: ["prettier", "format", "beautify", "code", "javascript", "typescript", "json", "css", "html"],
    isNew: true,
    isImplemented: true,
  },

  // ── BATCH 5: Design Tools (Part 5) ─────────────────────────────────────────
  { id: "color-blindness", name: "Colour Blindness Simulator", description: "Simulate protanopia, deuteranopia, tritanopia, achromatopsia on any image.", category: "design", icon: "Eye", tags: ["color","blindness","accessibility","wcag","simulate","vision"], isNew: true, isImplemented: true },
  { id: "clip-path", name: "CSS Clip-Path Generator", description: "Drag polygon handles to create clip-path shapes. Presets: triangle, hexagon, star.", category: "design", icon: "Scissors", tags: ["clip","path","css","polygon","shape","mask"], isNew: true, isImplemented: true },
  { id: "css-animation", name: "CSS Animation Generator", description: "Build @keyframes animations visually. Presets, easing, live preview, CSS output.", category: "design", icon: "PlayCircle", tags: ["css","animation","keyframes","transition","easing","hover"], isNew: true, isImplemented: true },
  { id: "icon-finder", name: "Icon Finder & Downloader", description: "Search 200,000+ icons from Iconify (Material, Heroicons, Tabler, Lucide).", category: "design", icon: "Star", tags: ["icon","svg","iconify","material","heroicons","tabler","lucide","phosphor"], isNew: true, isImplemented: true },
  { id: "type-scale", name: "Typography Scale Generator", description: "Generate type scales with musical ratios. CSS vars, Tailwind config, JSON.", category: "design", icon: "Type", tags: ["type","scale","typography","font","ratio","css","tailwind"], isNew: true, isImplemented: true },
  { id: "palette-advanced", name: "Image Palette Extractor", description: "Extract dominant colours from any image. Up to 24 swatches as hex.", category: "design", icon: "Palette", tags: ["palette","color","extract","image","dominant","hex"], isNew: true, isImplemented: true },
  { id: "color-bulk", name: "Bulk Colour Converter", description: "Convert multiple hex/rgb/hsl values at once to any format.", category: "design", icon: "RefreshCw", tags: ["color","bulk","convert","hex","rgb","hsl","oklch"], isNew: true, isImplemented: true },
  { id: "gradient-mesh", name: "Gradient Mesh Generator", description: "Create gradient mesh backgrounds using colour harmony schemes.", category: "design", icon: "Layers", tags: ["gradient","mesh","background","css","color","harmony"], isNew: true, isImplemented: true },
  { id: "svg-path", name: "SVG Path Editor", description: "Paste path data, see live preview, analyse commands, simplify, and convert.", category: "design", icon: "PenTool", tags: ["svg","path","d","editor","bezier","convert"], isNew: true, isImplemented: true },
  { id: "css-grid", name: "CSS Grid Generator", description: "Build grid layouts visually. Set columns, rows, gap, custom templates.", category: "design", icon: "Grid", tags: ["css","grid","layout","columns","rows","gap","template"], isNew: true, isImplemented: true },
  { id: "breakpoint-tester", name: "Responsive Breakpoint Tester", description: "Preview any URL at mobile, tablet, laptop, desktop viewports.", category: "web-seo", icon: "Smartphone", tags: ["responsive","breakpoint","mobile","tablet","desktop","viewport","preview"], isNew: true, isImplemented: true },

  // ── BATCH 6: Text & Code (Part 5) ──────────────────────────────────────────
  { id: "html-to-markdown", name: "HTML to Markdown Converter", description: "Convert HTML to clean Markdown using Turndown. Handles all common elements.", category: "text-code", icon: "FileDown", tags: ["html","markdown","convert","turndown","text"], isNew: true, isImplemented: true },
  { id: "yaml-json", name: "YAML ↔ JSON Converter", description: "Convert YAML to JSON and JSON to YAML. Real-time conversion with error highlighting.", category: "text-code", icon: "ArrowLeftRight", tags: ["yaml","json","convert","format","data"], isNew: true, isImplemented: true },
  { id: "xml-formatter", name: "XML Formatter & Validator", description: "Format, validate, and minify XML in-browser using DOMParser.", category: "text-code", icon: "FileCode", tags: ["xml","format","validate","minify","dom"], isNew: true, isImplemented: true },
  { id: "toml-json", name: "TOML ↔ JSON Converter", description: "Convert TOML to JSON and JSON to TOML. Handles nested structures.", category: "text-code", icon: "ArrowLeftRight", tags: ["toml","json","convert","config","rust","cargo"], isNew: true, isImplemented: true },
  { id: "sql-formatter", name: "SQL Formatter", description: "Format SQL queries for PostgreSQL, MySQL, SQLite, BigQuery, T-SQL.", category: "text-code", icon: "Database", tags: ["sql","format","postgresql","mysql","sqlite","query","beautify"], isNew: true, isImplemented: true },
  { id: "graphql-formatter", name: "GraphQL Schema Formatter", description: "Format and validate GraphQL SDL schemas, queries, and mutations.", category: "text-code", icon: "GitBranch", tags: ["graphql","schema","sdl","format","query","mutation"], isNew: true, isImplemented: true },
  { id: "env-parser", name: "Environment Variable Parser", description: "Parse .env files into a table, JSON, or cleaned export. Type inference.", category: "text-code", icon: "Terminal", tags: ["env","environment","variable","dotenv","parse","config"], isNew: true, isImplemented: true },
  { id: "http-status", name: "HTTP Status Code Reference", description: "Complete HTTP status codes with descriptions and usage guidance. 1xx–5xx.", category: "web-seo", icon: "Globe", tags: ["http","status","code","reference","api","rest","404","200"], isNew: true, isImplemented: true },
  { id: "keyboard-shortcuts", name: "Keyboard Shortcut Cheatsheet", description: "Searchable shortcut reference for Chrome, VS Code, macOS, and Windows.", category: "productivity", icon: "Keyboard", tags: ["keyboard","shortcut","hotkey","vscode","chrome","macos","windows"], isNew: true, isImplemented: true },

  // ── BATCH 7: Part 6 Final Tools ─────────────────────────────────────────────
  { id: "binary-visualiser", name: "Binary / Hex / Octal Visualiser", description: "Visualise integers, floats (IEEE 754), text (UTF-8), and colours at bit level.", category: "text-code", icon: "Binary", tags: ["binary","hex","octal","ieee754","float","utf8","bits","visualise"], isNew: true, isImplemented: true },
  { id: "file-tools", name: "File Size Analyser & Batch Renamer", description: "Analyse file sizes and types. Preview batch rename operations.", category: "productivity", icon: "Files", tags: ["file","size","rename","batch","analyser","organise"], isNew: true, isImplemented: true },
  { id: "morse-code", name: "Morse Code Translator", description: "Translate text to Morse code. Hear it via Web Audio API with WPM control.", category: "text-code", icon: "Radio", tags: ["morse","code","translate","audio","wpm","dots","dashes"], isNew: true, isImplemented: true },
  { id: "slug-generator", name: "URL Slug Generator", description: "Generate URL-safe slugs from text. Multiple separators, bulk CSV export.", category: "web-seo", icon: "Link", tags: ["slug","url","permalink","seo","kebab-case","camelCase","bulk"], isNew: true, isImplemented: true },
  { id: "css-specificity", name: "CSS Specificity Calculator", description: "Calculate A/B/C/D specificity for any CSS selector. Compare two selectors.", category: "design", icon: "Calculator", tags: ["css","specificity","selector","id","class","element","cascade"], isNew: true, isImplemented: true },
  { id: "json-schema", name: "JSON Schema Validator", description: "Validate JSON data against a JSON Schema using AJV. Infer schema from data.", category: "text-code", icon: "ShieldCheck", tags: ["json","schema","validate","ajv","draft7","types"], isNew: true, isImplemented: true },
  { id: "readability", name: "Readability Scorer", description: "Score text with 6 algorithms: Flesch, FK, Fog, SMOG, Coleman-Liau, ARI.", category: "writing", icon: "BookOpen", tags: ["readability","flesch","fog","smog","ari","grade","text","writing"], isNew: true, isImplemented: true },
  { id: "text-to-handwriting", name: "Text to Handwriting", description: "Convert typed text to handwritten-style images. Multiple fonts, download PNG.", category: "writing", icon: "PenLine", tags: ["handwriting","text","image","canvas","font","google","png"], isNew: true, isImplemented: true },
  { id: "data-url", name: "Data URL Encoder / Decoder", description: "Encode files to data URLs or decode data URLs back to files.", category: "text-code", icon: "FileCode2", tags: ["data","url","base64","encode","decode","mime","datauri"], isNew: true, isImplemented: true },
  { id: "speed-test", name: "Network Speed Test", description: "Measure download, upload, ping, jitter & bufferbloat against the nearest Cloudflare edge. Live gauge, connection info, and history.", category: "productivity", icon: "Wifi", tags: ["speed","test","network","ping","download","upload","bandwidth","latency","jitter","bufferbloat"], isNew: true, isImplemented: true },
];

export function getToolById(id: string): Tool | undefined {
  return tools.find((t) => t.id === id);
}

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return tools.filter((t) => t.category === category);
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase().trim();
  if (!q) return tools;
  return tools.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.tags.some((tag) => tag.includes(q))
  );
}
